# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # configure resolvers
    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path: 
                web_root : "%kernel.project_dir%/public"    
    filter_sets:
        miniature:
            quality: 75
            filters:
                thumbnail:
                    size: [200, 150]
                    mode: outbound
